# Generated by Django 3.2.3 on 2021-09-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_friendrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='user',
        ),
    ]
