# Generated by Django 3.2.3 on 2021-08-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_qrcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransferBalance',
        ),
    ]
